(function(){
'use strict';
if('scrollRestoration' in history)history.scrollRestoration='manual';
addEventListener('pageshow',()=>scrollTo(0,0));
const TXT={
fr:{question:"Possèdes-tu déjà le matériel PokeTama ?",questionSub:"Choisis ton parcours pour afficher uniquement ce dont tu as besoin.",yes:"Oui, je l’ai déjà",no:"Non, je veux le configurer",configEye:"CRÉE TON POKETAMA",configTitle:"Choisis ta version",configLead:"Fais tourner le modèle, choisis ta Ball puis ajoute l’écran et la batterie.",ball:"Modèle de coque",poke:"Poké Ball",great:"Super Ball",ultra:"Hyper Ball",master:"Master Ball",screen:"Écran rond AMOLED",battery:"Batterie rechargeable",with:"Avec",without:"Sans",drag:"Glisse pour faire tourner",summary:"Ta configuration",included:"Comprend la coque {0}, {1} écran et {2} batterie.",yesWord:"avec",noWord:"sans",price:"Prix",add:"Ajouter au panier",adding:"Ajout en cours…",added:"Ajouté au panier",cartError:"Impossible d’ajouter cette configuration. Vérifie le produit Shopify.",modelError:"Modèle 3D indisponible",change:"Changer de parcours"},
en:{question:"Do you already own the PokeTama hardware?",questionSub:"Choose your path to see only what you need.",yes:"Yes, I already own it",no:"No, I want to configure it",configEye:"BUILD YOUR POKETAMA",configTitle:"Choose your version",configLead:"Rotate the model, choose your Ball, then add the screen and battery.",ball:"Shell model",poke:"Poké Ball",great:"Great Ball",ultra:"Ultra Ball",master:"Master Ball",screen:"Round AMOLED screen",battery:"Rechargeable battery",with:"With",without:"Without",drag:"Drag to rotate",summary:"Your configuration",included:"Includes the {0} shell, {1} screen and {2} battery.",yesWord:"with",noWord:"without",price:"Price",add:"Add to cart",adding:"Adding…",added:"Added to cart",cartError:"Unable to add this configuration. Check the Shopify product.",modelError:"3D model unavailable",change:"Change path"},
es:{question:"¿Ya tienes el hardware PokeTama?",questionSub:"Elige tu recorrido para ver solo lo que necesitas.",yes:"Sí, ya lo tengo",no:"No, quiero configurarlo",configEye:"CREA TU POKETAMA",configTitle:"Elige tu versión",configLead:"Gira el modelo, elige tu Ball y añade pantalla y batería.",ball:"Modelo de carcasa",poke:"Poké Ball",great:"Super Ball",ultra:"Ultra Ball",master:"Master Ball",screen:"Pantalla AMOLED redonda",battery:"Batería recargable",with:"Con",without:"Sin",drag:"Desliza para girar",summary:"Tu configuración",included:"Incluye carcasa {0}, {1} pantalla y {2} batería.",yesWord:"con",noWord:"sin",price:"Precio",add:"Añadir al carrito",adding:"Añadiendo…",added:"Añadido al carrito",cartError:"No se puede añadir esta configuración. Revisa el producto Shopify.",modelError:"Modelo 3D no disponible",change:"Cambiar recorrido"},
de:{question:"Besitzt du bereits die PokeTama-Hardware?",questionSub:"Wähle deinen Weg und sieh nur die passenden Inhalte.",yes:"Ja, ich habe sie bereits",no:"Nein, ich möchte konfigurieren",configEye:"BAUE DEIN POKETAMA",configTitle:"Wähle deine Version",configLead:"Drehe das Modell, wähle deinen Ball und ergänze Display und Akku.",ball:"Gehäusemodell",poke:"Pokéball",great:"Superball",ultra:"Hyperball",master:"Meisterball",screen:"Rundes AMOLED-Display",battery:"Wiederaufladbarer Akku",with:"Mit",without:"Ohne",drag:"Zum Drehen ziehen",summary:"Deine Konfiguration",included:"Enthält {0}-Gehäuse, {1} Display und {2} Akku.",yesWord:"mit",noWord:"ohne",price:"Preis",add:"In den Warenkorb",adding:"Wird hinzugefügt…",added:"Zum Warenkorb hinzugefügt",cartError:"Diese Konfiguration konnte nicht hinzugefügt werden. Shopify-Produkt prüfen.",modelError:"3D-Modell nicht verfügbar",change:"Auswahl ändern"},
it:{question:"Possiedi già l’hardware PokeTama?",questionSub:"Scegli il percorso per vedere solo ciò che ti serve.",yes:"Sì, ce l’ho già",no:"No, voglio configurarlo",configEye:"CREA IL TUO POKETAMA",configTitle:"Scegli la tua versione",configLead:"Ruota il modello, scegli la Ball e aggiungi schermo e batteria.",ball:"Modello scocca",poke:"Poké Ball",great:"Mega Ball",ultra:"Ultra Ball",master:"Master Ball",screen:"Schermo AMOLED rotondo",battery:"Batteria ricaricabile",with:"Con",without:"Senza",drag:"Trascina per ruotare",summary:"La tua configurazione",included:"Include scocca {0}, {1} schermo e {2} batteria.",yesWord:"con",noWord:"senza",price:"Prezzo",add:"Aggiungi al carrello",adding:"Aggiunta…",added:"Aggiunto al carrello",cartError:"Impossibile aggiungere la configurazione. Controlla il prodotto Shopify.",modelError:"Modello 3D non disponibile",change:"Cambia percorso"},
pt:{question:"Já tens o hardware PokeTama?",questionSub:"Escolhe o percurso para veres apenas o que precisas.",yes:"Sim, já tenho",no:"Não, quero configurar",configEye:"CRIA O TEU POKETAMA",configTitle:"Escolhe a tua versão",configLead:"Roda o modelo, escolhe a Ball e adiciona ecrã e bateria.",ball:"Modelo da caixa",poke:"Poké Ball",great:"Super Ball",ultra:"Ultra Ball",master:"Master Ball",screen:"Ecrã AMOLED redondo",battery:"Bateria recarregável",with:"Com",without:"Sem",drag:"Arrasta para rodar",summary:"A tua configuração",included:"Inclui caixa {0}, {1} ecrã e {2} bateria.",yesWord:"com",noWord:"sem",price:"Preço",add:"Adicionar ao carrinho",adding:"A adicionar…",added:"Adicionado ao carrinho",cartError:"Não foi possível adicionar esta configuração. Verifica o produto Shopify.",modelError:"Modelo 3D indisponível",change:"Mudar percurso"}}
const state={ball:'poke',screen:true,battery:true};
const BACK={fr:'Retour à l’accueil',en:'Back to home',es:'Volver al inicio',de:'Zurück zum Start',it:'Torna all’inizio',pt:'Voltar ao início'};
const lang=()=>TXT[document.documentElement.lang]||TXT.fr;
const fmt=(s,...v)=>s.replace(/\{(\d+)\}/g,(_,i)=>v[i]);
const key=()=>`${state.screen?1:0}${state.battery?1:0}`;
const variant=()=>{let v=state.ball;if(state.screen&&state.battery)v+='-screen-battery';else if(state.screen)v+='-screen';else if(state.battery)v+='-battery';return v};
function create(){
 const hero=document.querySelector('.hero');if(!hero||document.querySelector('.ownership-gate'))return;
 const gate=document.createElement('section');gate.className='ownership-gate';gate.innerHTML='<h2 data-c="question"></h2><p data-c="questionSub"></p><div class="ownership-actions"><button class="yes" data-path="install" data-c="yes"></button><button class="no" data-path="config" data-c="no"></button></div>';hero.after(gate);
 const install=document.createElement('div');install.id='install-path';install.className='path-panel';install.hidden=true;let node=gate.nextElementSibling;const footer=document.querySelector('footer');while(node&&node!==footer){const next=node.nextElementSibling;install.appendChild(node);node=next}const installBack=document.createElement('button');installBack.className='change-path install-back';installBack.setAttribute('data-back','');install.appendChild(installBack);gate.after(install);
 const cfg=document.createElement('section');cfg.id='config-path';cfg.className='configurator path-panel';cfg.hidden=true;cfg.innerHTML='<div class="configurator-head"><div class="eyebrow" data-c="configEye"></div><h2 data-c="configTitle"></h2><p data-c="configLead"></p></div><div class="config-grid"><div class="ball-stage" id="ball-stage"><model-viewer class="product-model" id="product-model" src="models/poketama-poke-screen-battery.glb?v=9.58.1" camera-controls orientation="0deg -90deg 0deg" shadow-intensity="1.1" shadow-softness=".9" exposure="1.05" camera-orbit="30deg 64deg 5m" field-of-view="30deg" min-camera-orbit="auto auto 3.5m" max-camera-orbit="auto auto 7m" interaction-prompt="none"></model-viewer><span class="model-loading"></span><span class="drag-hint" data-c="drag"></span></div><div class="config-controls"><div class="config-block"><h3 data-c="ball"></h3><div class="choice-row four" data-group="ball"><button class="config-choice active" data-value="poke" data-c="poke"></button><button class="config-choice" data-value="great" data-c="great"></button><button class="config-choice" data-value="ultra" data-c="ultra"></button><button class="config-choice" data-value="master" data-c="master"></button></div></div><div class="config-block"><h3 data-c="screen"></h3><div class="choice-row" data-group="screen"><button class="config-choice active" data-value="true" data-c="with"></button><button class="config-choice" data-value="false" data-c="without"></button></div></div><div class="config-block"><h3 data-c="battery"></h3><div class="choice-row" data-group="battery"><button class="config-choice active" data-value="true" data-c="with"></button><button class="config-choice" data-value="false" data-c="without"></button></div></div><div class="config-summary"><strong data-c="summary"></strong><p id="config-description"></p></div></div></div><button class="change-path" data-c="change"></button>';
 const configBack=cfg.querySelector('.change-path');configBack.removeAttribute('data-c');configBack.setAttribute('data-back','');gate.after(cfg);bind(gate,cfg);translate();
 const model=cfg.querySelector('#product-model');model.addEventListener('load',()=>cfg.querySelector('.ball-stage').classList.remove('loading','model-error'));model.addEventListener('error',()=>{cfg.querySelector('.ball-stage').classList.add('model-error');cfg.querySelector('.model-loading').textContent=lang().modelError});
}
function show(which){document.querySelector('#install-path').hidden=which!=='install';document.querySelector('#config-path').hidden=which!=='config';document.querySelector('.ownership-gate').hidden=true;parent.postMessage({type:'poketama-path-change',path:which},'*');setTimeout(reportHeight,50)}
function reset(){document.querySelector('#install-path').hidden=true;document.querySelector('#config-path').hidden=true;document.querySelector('.ownership-gate').hidden=false;parent.postMessage({type:'poketama-path-change',path:'gate'},'*');document.querySelector('.hero').scrollIntoView({behavior:'smooth',block:'start'});setTimeout(reportHeight,350)}
function syncChoices(){document.querySelectorAll('[data-group]').forEach(row=>{const group=row.dataset.group;row.querySelectorAll('button').forEach(b=>b.classList.toggle('active',group==='ball'?b.dataset.value===state.ball:(b.dataset.value==='true')===state[group]))})}
function bind(g,c){g.querySelectorAll('[data-path]').forEach(b=>b.onclick=()=>show(b.dataset.path));document.querySelectorAll('.change-path').forEach(b=>b.onclick=reset);c.querySelectorAll('.config-choice').forEach(b=>b.onclick=()=>{const group=b.closest('[data-group]').dataset.group;state[group]=group==='ball'?b.dataset.value:b.dataset.value==='true';syncChoices();render()})}
function render(){const t=lang(),model=document.querySelector('#product-model');if(!model)return;const src=`models/poketama-${variant()}.glb?v=9.58.1`;if(model.getAttribute('src')!==src){document.querySelector('.ball-stage').classList.add('loading');model.setAttribute('src',src)}model.setAttribute('alt',`${t[state.ball]} PokeTama`);document.querySelector('#config-description').textContent=fmt(t.included,t[state.ball],state.screen?t.yesWord:t.noWord,state.battery?t.yesWord:t.noWord);parent.postMessage({type:'poketama-config-change',key:key(),ball:state.ball,ballLabel:t[state.ball],screen:state.screen,battery:state.battery},'*')}
function translate(){const t=lang(),code=document.documentElement.lang in BACK?document.documentElement.lang:'fr';document.querySelectorAll('[data-c]').forEach(e=>e.textContent=t[e.dataset.c]||e.dataset.c);document.querySelectorAll('[data-back]').forEach(e=>e.textContent=BACK[code]);render();reportHeight()}
function reportHeight(){const wrap=document.querySelector('.wrap');if(window.parent!==window&&wrap)parent.postMessage({type:'poketama-shopify-height',height:Math.ceil(wrap.getBoundingClientRect().bottom)},'*')}
document.addEventListener('DOMContentLoaded',create);new MutationObserver(translate).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
})();
